### ISSUE TITLE
Always get a warning message in the console when you connect

### ISSUE THREAD

**Issue by dinushay** [IvenGe/Minecraft_SimpleWebServer#1]
I always get a warning message when someone connects to the web server. The message doesn't look deliberate either. 

```diff
! [Sat 11:32:49 WARN ] Exception in thread "Thread-258" java.lang.NullPointerException: Cannot invoke "String.toString()" because the return value of "java.util.HashMap.get(Object)" is null
! [Sat 11:32:49 WARN ] 	at WebServer_0.3-SNAPSHOT.jar//be.dailysurvival.webserver.Connection.sendResponse(Connection.java:113)
! [Sat 11:32:49 WARN ] 	at WebServer_0.3-SNAPSHOT.jar//be.dailysurvival.webserver.Connection.run(Connection.java:191)
! [Sat 11:32:49 WARN ] 	at java.base/java.lang.Thread.run(Thread.java:833)
```

The website works without any problems, but this message is constantly spamming my console

**Comment by IvenGe** [comment]
Can you please try this version ?   you have to first unzip it because otherwise, I cant upload it here
[WebServer_fixed-1.0-SNAPSHOT (6).zip](https://github.com/IvenGe/Minecraft_SimpleWebServer/files/13843241/WebServer_fixed-1.0-SNAPSHOT.6.zip)
